INSERT INTO HERO(NOME_HEROI) VALUES ('Batman');
INSERT INTO HERO(NOME_HEROI) VALUES ('Homem de ferro');
INSERT INTO HERO(NOME_HEROI) VALUES ('Groot');
INSERT INTO HERO(NOME_HEROI) VALUES ('Thor');

insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Biliónario', 1);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Biliónario', 2);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Deus do trovão', 4);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Gênio da tecnologia', 2);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Usa armaduras de alta tecnologia', 1);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Super Força', 3);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Usa armaduras de alta tecnologia', 2);
insert into PODERES (NOME_PODER, HERO_ID_HEROI) VALUES ('Regeneração celular acelerada', 3);

INSERT INTO PARCEIRO (NOME_PARCEIRO, HERO_ID_HEROI) VALUES ('Rocket', 3);
INSERT INTO PARCEIRO (NOME_PARCEIRO, HERO_ID_HEROI) VALUES ('Máquina de combate', 2);
INSERT INTO PARCEIRO (NOME_PARCEIRO, HERO_ID_HEROI) VALUES ('Robin', 1);
INSERT INTO PARCEIRO (NOME_PARCEIRO, HERO_ID_HEROI) VALUES ('Hulk', 4);

