INSERT INTO HERO (NOME) VALUES ('Batman');
INSERT INTO HERO (NOME) VALUES ('Homem de ferro');
INSERT INTO HERO (NOME) VALUES ('Homem Formiga');

INSERT INTO PODERES (NOME_PODER) VALUES ('Artes Marciais');
INSERT INTO PODERES (NOME_PODER) VALUES ('Gênio da tecnologia');
INSERT INTO PODERES (NOME_PODER) VALUES ('Usa partículas Pym para mudar de tamanho');

INSERT INTO PODER_HEROI (HERO_ID_HEROI, PODERES_ID_PODER) VALUES ( 1, 1);
INSERT INTO PODER_HEROI (HERO_ID_HEROI, PODERES_ID_PODER) VALUES ( 2, 2);
INSERT INTO PODER_HEROI (HERO_ID_HEROI, PODERES_ID_PODER) VALUES ( 3, 3);

INSERT INTO PARCEIRO (NOME_PARCEIRO) VALUES ('Robin');
INSERT INTO PARCEIRO (NOME_PARCEIRO) VALUES ('Máquina de Combate');
INSERT INTO PARCEIRO (NOME_PARCEIRO) VALUES ('Vespa');


